version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./infra/dev/Dockerfile
    ports:
      - '8080:8080'
    working_dir: /opt/app
    volumes:
      - ./cmd:/opt/app/cmd
      - ./gen:/opt/app/gen
      - ./internal:/opt/app/internal
      - ./static:/opt/app/static
      - ./go.mod:/opt/app/go.mod
      - ./go.sum:/opt/app/go.sum
